Last login: Tue Feb  4 13:41:11 on ttys000
bash
$ bash
bash-3.2$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvchp   Bound    pvc-7f2e1abf-466b-11ea-af7a-025000000001   1Gi        RWO            hostpath       22h
bash-3.2$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM           STORAGECLASS   REASON   AGE
pvc-7f2e1abf-466b-11ea-af7a-025000000001   1Gi        RWO            Delete           Bound    default/pvchp   hostpath                22h
bash-3.2$ kubectl get sc
NAME                 PROVISIONER          AGE
hostpath (default)   docker.io/hostpath   71d
bash-3.2$ kubectl get pvc pvchp -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"4beb61d2-463f-11ea-ae40-acde48001122","leaseDurationSeconds":15,"acquireTime":"2020-02-03T09:56:49Z","renewTime":"2020-02-03T09:56:51Z","leaderTransitions":0}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvchp","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvchp
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pvchp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-7f2e1abf-466b-11ea-af7a-025000000001
status: {}
bash-3.2$ kubectl get pv pvc-7f2e1abf-466b-11ea-af7a-025000000001 -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    docker.io/hostpath: /Users/rvaish/.docker/Volumes/pvchp/pvc-7f2e1abf-466b-11ea-af7a-025000000001
    pv.kubernetes.io/provisioned-by: docker.io/hostpath
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-7f2e1abf-466b-11ea-af7a-025000000001
  selfLink: /api/v1/persistentvolumes/pvc-7f2e1abf-466b-11ea-af7a-025000000001
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvchp
    namespace: default
    resourceVersion: "1166675"
    uid: 7f2e1abf-466b-11ea-af7a-025000000001
  hostPath:
    path: /Users/rvaish/.docker/Volumes/pvchp/pvc-7f2e1abf-466b-11ea-af7a-025000000001
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
status: {}
bash-3.2$ kubectl get sc hostpath -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: null
  name: hostpath
  selfLink: /apis/storage.k8s.io/v1/storageclasses/hostpath
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
bash-3.2$ 
